[build]
builder = "nixpacks"
buildCommand = "npm install --no-package-lock && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-package-lock"]

[phases.build]
cmds = ["npm run build"] 